### ISSUE TITLE
Tracking: Season 0

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/alphanet#105]
A checklist of things needed for Alphanet season 0 outside of what we already have (e.g. EOF, 7702, BLS, secp)

```[tasklist]
### reth
- [ ] https://github.com/paradigmxyz/reth/issues/10446
- [x] EIP-2935 changes (see https://github.com/paradigmxyz/reth/issues/10079)
- [ ] Optimism P2P fixes
- [x] Engine experimental (native support in Alphanet): https://github.com/paradigmxyz/reth/issues/8742
- [x] Allow payloads without requests for Prague
```
```[tasklist]
### alloy
- [ ] https://github.com/alloy-rs/alloy/issues/1174
```
```[tasklist]
### revm
- [ ] https://github.com/bluealloy/revm/pull/1695
```
```[tasklist]
### Alphanet
- [ ] https://github.com/paradigmxyz/alphanet/issues/103
- [x] Bump 7702 patches for op-node
```

When all checklists are done we need to ensure we are on the latest reth with the latest revm and alloy

**Comment by onbjerg** [comment]
Closing this as everything is done except for P2P, which is unclear if there are fixes needed, and if so, what, so we should just track that separately
