### ISSUE TITLE
EIP-2537: Precompile for BLS12-381 curve operations

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/alphanet#11]
We should add EIP-2537, spec here:
https://eips.ethereum.org/EIPS/eip-2537

The precompile has ABIs for the following operations:
* G1 addition
* G1 multiplication
* G1 multiexponentiation
* G2 addition
* G2 multiplication
* G2 multiexponentiation
* Pairing
* Mapping Fp element to G1 point 
* Mapping Fp element to G2 point

There are also some test vectors, although this will need to be tested more than with just these:
https://eips.ethereum.org/assets/eip-2537/bench_vectors

We use `blst` in `c-kzg-4844`, and it has rust bindings, so that could be used here as well:
https://github.com/supranational/blst
```[tasklist]
### Tasks
- [x] BLS12_G1ADD: https://github.com/paradigmxyz/alphanet/pull/17
- [x] BLS12_G1MUL: https://github.com/paradigmxyz/alphanet/pull/19
- [x] BLS12_G1MULTIEXP: https://github.com/paradigmxyz/alphanet/pull/31
- [x] BLS12_G2ADD: https://github.com/paradigmxyz/alphanet/pull/32
- [x] BLS12_G2MUL: https://github.com/paradigmxyz/alphanet/pull/33
- [x] BLS12_G2MULTIEXP: https://github.com/paradigmxyz/alphanet/pull/34
- [x] BLS12_PAIR: https://github.com/paradigmxyz/alphanet/pull/35
- [x] BLS12_MAP_FP_TO_G1: https://github.com/paradigmxyz/alphanet/pull/36
- [x] BLS12_MAP_FP_TO_G2: https://github.com/paradigmxyz/alphanet/pull/37
```
