### ISSUE TITLE
Tracking: EXP-0001

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/alphanet#126]
We want to add the following endpoints for experiment 1 on AlphaNet to facilitate gas sponsoring of EIP-7702 delegations and further interactions with EIP-7702 EOAs:

- `wallet_getCapabilities` [(EIP-5792)](https://eips.ethereum.org/EIPS/eip-5792)
- `wallet_sendTransaction`

The sequencer also needs two additional configuration values, set via environment variables:

- One for the sequencer private key used for gas sponsoring (`EXP0001_PK`)
- One for the contract used for delegations in experiment 1 (`EXP0001_ADDRESS`)

For more context, see https://hackmd.io/@qCfD_jzVSzmS6lHmidSeRQ/HkhytUoCA

# Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/alphanet/issues/132
- [ ] https://github.com/paradigmxyz/alphanet/issues/131
- [ ] https://github.com/paradigmxyz/alphanet/issues/133
- [x] Document setting up EXP-0001, i.e. deploying the contract and configuring the sequencer
```

**Comment by jxom** [comment]
Suggest changes based on slack convo:

> We want to add the following endpoints for experiment 1 on AlphaNet to facilitate gas sponsoring of EIP-7702 delegations > and further interactions with EIP-7702 EOAs:
>
> - `wallet_getCapabilities` [(EIP-5792)](https://eips.ethereum.org/EIPS/eip-5792)
> - ~`wallet_auth`~
> - ~`wallet_sendCalls` [(EIP-5792)](https://eips.ethereum.org/EIPS/eip-5792)~
> - `wallet_sendTransaction`

**Comment by onbjerg** [comment]
Updated the issue based on the above

**Comment by onbjerg** [comment]
Moving to Odyssey in Ithaca org
