### ISSUE TITLE
Tracking: EXP-0001

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/alphanet#127]
We want to add the following endpoints for experiment 1 on AlphaNet to facilitate gas sponsoring of EIP-7702 delegations and further interactions with EIP-7702 EOAs:

- `wallet_getCapabilities` [(EIP-5792)](https://eips.ethereum.org/EIPS/eip-5792)
- `wallet_auth`
- `wallet_sendCalls` [(EIP-5792)](https://eips.ethereum.org/EIPS/eip-5792)

The sequencer also needs two additional configuration values, set via environment variables:

- One for the sequencer private key used for gas sponsoring (`EXP0001_PK`)
- One for the contract used for delegations in experiment 1 (`EXP0001_ADDRESS`)

The address is primarily used in `wallet_getCapabilities`.

For more context, see https://hackmd.io/@qCfD_jzVSzmS6lHmidSeRQ/HkhytUoCA

# Tasks

```[tasklist]
### Tasks
- [ ] Implement `wallet_getCapabilities`
- [ ] Implement `wallet_auth`
- [ ] Implement `wallet_sendCalls`
- [ ] Document setting up EXP-0001
```

**Comment by onbjerg** [comment]
Duplicate of #126 (thanks GitHub)
